# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0002_auto_20161218_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='profile_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user_profile', to='user_dashboard_app.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_commentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_commentor', to='user_dashboard_app.User'),
        ),
    ]
