# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0003_auto_20161218_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent_message',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
