# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0004_auto_20161218_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_details', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard_app.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_profile', to='user_dashboard_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_commentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_commentor', to='user_dashboard_app.User'),
        ),
    ]
